# Proxmox installation specific
STORAGE_POOL: "local-lvm"

# Region & Timezone
TIMEZONE: "Europe/Budapest"

# VM definitions
OPENWRT:
  VM_VMID: 10000
  VM_NAME: "template-openwrt-{{ VERSION }}"
  VM_MACHINE: q35
  VM_CPU: host
  VM_CORES: 1
  VM_DISPLAY: serial0
  VM_MEMORY: 256
  VM_ROOT_SIZE: "2G"
  VM_BRIDGE: "vmbr0"
  PACKAGES:
    - nano
    - tcpdump

GUEST_DISTRIBUTION: "suse" # Target distro: suse, ubuntu
GUEST:
  VM_VMID: 10001
  VM_NAME: "template-{{ GUEST_DISTRIBUTION }}-{{ VERSION }}"
  VM_MACHINE: q35
  VM_CPU: host
  VM_CORES: 2
  VM_DISPLAY: vmware
  VM_MEMORY: 1024
  VM_ROOT_SIZE: "10G"
  VM_BRIDGE: "vmbr0"
  PACKAGES:   # Pre-install packages
    - qemu-guest-agent
    - sudo
    - traceroute
    - htop
    - iotop
    - nano
