---
### Environment validation: distro
- name: Load distribution-specific variables
  hosts: localhost
  become: no
  gather_facts: false
  tasks:
    - name: Check if distribution variable file exists
      stat:
        path: "{{ playbook_dir }}/../vars/distro-{{ GUEST_DISTRIBUTION }}.yml"
      register: DISTRO_FILE

    - name: Fail if distribution variable file does not exist
      fail:
        msg: "Distribution variable file '{{ playbook_dir }}/../vars/distro-{{ GUEST_DISTRIBUTION }}.yml' not found."
      when: not DISTRO_FILE.stat.exists

    - name: Load distribution-specific variables dynamically based on DISTRIBUTION variable
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/../vars/distro-{{ GUEST_DISTRIBUTION }}.yml"

    - name: Set global facts for all hosts
      ansible.builtin.set_fact:
        VERSION: "{{ VERSION }}"
        DESTINATION_PATH: "{{ DESTINATION_PATH }}"
        IMAGE_URL: "{{ IMAGE_URL }}"
        PACKAGE_UPDATE_COMMAND: "{{ PACKAGE_UPDATE_COMMAND }}"
        PACKAGE_UPGRADE_COMMAND: "{{ PACKAGE_UPGRADE_COMMAND }}"
      delegate_to: "{{ item }}"
      delegate_facts: true
      loop: "{{ groups['all'] }}"

      
### Proxmox validation
- name: Check if host is running Proxmox
  hosts: all
  become: yes
  gather_facts: false
  tasks:
    - name: Check Proxmox version
      ansible.builtin.command:
        cmd: pveversion
      register: PVE_VERSION
      failed_when: PVE_VERSION.rc != 0
      changed_when: false

    - name: Verify Proxmox is installed
      ansible.builtin.assert:
        that:
          - "'pve-manager' in PVE_VERSION.stdout"
        fail_msg: "This host does not appear to be running Proxmox VE"
        success_msg: "Proxmox VE detected: {{ PVE_VERSION.stdout }}"

### Playbook start
- name: Prepare environment on proxmox
  hosts: all
  become: yes
  gather_facts: false
  tasks:
    - name: Prepare environment
      block:
        - name: Ensure destination directory exists
          ansible.builtin.file:
            path: "/var/lib/vz/template/iso"
            state: directory
            mode: '0755'

        - name: Install libguestfs-tools
          ansible.builtin.apt:
            name: libguestfs-tools
            state: present
            update_cache: yes
          register: APT_RESULT
          until: APT_RESULT is success
          retries: 3
          delay: 5

    - name: Prepare cloud image
      block:
        - name: Check if cloud image exists
          ansible.builtin.stat:
            path: "{{ DESTINATION_PATH }}"
          register: IMAGE_STAT

        - name: Show image URL before downloading
          ansible.builtin.debug:
            msg: "Downloading cloud image from: {{ IMAGE_URL }}"

        - name: Download and verify cloud image
          ansible.builtin.get_url:
            url: "{{ IMAGE_URL }}"
            dest: "{{ DESTINATION_PATH }}"
            mode: '0644'
          when: >
            not IMAGE_STAT.stat.exists
          register: DOWNLOAD_RESULT

        - name: Create a copy of the image
          ansible.builtin.copy:
            src: "{{ DESTINATION_PATH }}"
            dest: "{{ DESTINATION_PATH }}.modified"
            remote_src: yes

        - name: Resize copied cloud image if needed
          ansible.builtin.shell: |
            current_size=$(qemu-img info {{ DESTINATION_PATH }}.modified | grep 'virtual size' | awk '{print $3}')
            if [ "$current_size" != "{{ GUEST.VM_ROOT_SIZE }}" ]; then
              qemu-img resize -f qcow2 {{ DESTINATION_PATH }}.modified {{ GUEST.VM_ROOT_SIZE }}
            fi
          register: RESIZE_RESULT
          changed_when: RESIZE_RESULT.stdout != ""

        - name: Install packages in the copied cloud image
          ansible.builtin.command:
            cmd: >
              virt-customize -a {{ DESTINATION_PATH }}.modified
              --install {{ GUEST.PACKAGES | join(",") }}
              --run-command '{{ PACKAGE_UPDATE_COMMAND }} && {{ PACKAGE_UPGRADE_COMMAND }}'

        - name: Set timezone to {{ TIMEZONE }}
          ansible.builtin.command:
            cmd: virt-customize -a {{ DESTINATION_PATH }}.modified --timezone "{{ TIMEZONE }}"
          register: TIMEZONE_RESULT
          changed_when: TIMEZONE_RESULT.rc == 0

        - name: Copy custom cloud-init configuration
          ansible.builtin.copy:
            src: "{{ playbook_dir }}/../cloud-init/cloud-{{ GUEST_DISTRIBUTION }}.cfg"
            dest: "/tmp/{{ GUEST.VM_VMID }}-cloud.cfg"
            mode: '0644'

        - name: Replace original cloud.cfg in VM
          ansible.builtin.command:
            cmd: >
              virt-customize -a {{ DESTINATION_PATH }}.modified 
              --upload "/tmp/{{ GUEST.VM_VMID }}-cloud.cfg:/etc/cloud/cloud.cfg"

        - name: Disable MOTD messages in image
          ansible.builtin.command:
            cmd: >
              virt-customize -v -a {{ DESTINATION_PATH }}.modified 
              --run-command 'chmod -x /etc/update-motd.d/*'
              --run-command 'chmod +x /etc/update-motd.d/50-landscape-sysinfo'
              --run-command 'echo "ENABLED=0" > /etc/default/motd-news'
          ignore_errors: yes
          when: GUEST_DISTRIBUTION == 'ubuntu'

    - name: Check existing vm
      community.general.proxmox_vm_info:
        api_user: "{{ PROXMOX_USER }}@pam"
        api_password: "{{ PROXMOX_PASSWORD }}"
        api_host: "{{ PROXMOX_HOST }}"
        node: "{{ PROXMOX_NODE }}"
        vmid: "{{ GUEST.VM_VMID }}"
      register: VM_INFO

    - name: Stop and remove existing VM if it exists
      when: VM_INFO.proxmox_vms | length > 0
      block:
        - name: Stop existing VM if running
          ansible.builtin.command:
            cmd: "qm stop {{ GUEST.VM_VMID }}"
          register: STOP_RESULT
          changed_when: STOP_RESULT.rc == 0
          when: VM_INFO.proxmox_vms[0].status == 'running'
          ignore_errors: yes

        - name: Remove existing VM
          ansible.builtin.command:
            cmd: "qm destroy {{ GUEST.VM_VMID }} --purge"
          register: DESTROY_RESULT
          until: DESTROY_RESULT.rc == 0
          retries: 3
          delay: 5

    - name: Create and configure new VM
      block:
        - name: Create new VM in Proxmox
          community.general.proxmox_kvm:
            api_user: "{{ PROXMOX_USER }}@pam"
            api_password: "{{ PROXMOX_PASSWORD }}"
            api_host: "{{ PROXMOX_HOST }}"
            node: "{{ PROXMOX_NODE }}"
            vmid: "{{ GUEST.VM_VMID }}"
            name: "{{ GUEST.VM_NAME }}"
            machine: "{{ GUEST.VM_MACHINE }}"
            memory: "{{ GUEST.VM_MEMORY }}"
            cpu: "{{ GUEST.VM_CPU }}"
            cores: "{{ GUEST.VM_CORES }}"
            sockets: 1
            vga: "{{ GUEST.VM_DISPLAY }}"
            ostype: "l26"
            net:
              net0: "virtio,bridge={{ GUEST.VM_BRIDGE }},firewall=1"
            scsihw: "virtio-scsi-pci"
            ide:
              ide0: "{{ STORAGE_POOL }}:cloudinit"
            agent: 1
            serial:
              serial0: socket
            state: present

        - name: Import and configure disk
          ansible.builtin.shell: >
            qm importdisk {{ GUEST.VM_VMID }} {{ DESTINATION_PATH }}.modified {{ STORAGE_POOL }} &&
            qm set {{ GUEST.VM_VMID }}
            --virtio0 {{ STORAGE_POOL }}:vm-{{ GUEST.VM_VMID }}-disk-0,discard=on,iothread=1
            --boot c --bootdisk virtio0 
          args:
            creates: "/var/lib/vz/images/{{ GUEST.VM_VMID }}/vm-{{ GUEST.VM_VMID }}-disk-0.raw"

        - name: Configure cloud-init
          block:
            - name: Create temporary SSH key file
              ansible.builtin.copy:
                content: "{{ SSH_PUBLIC_KEYS }}"
                dest: "/tmp/ssh_key_{{ GUEST.VM_VMID }}.pub"
                mode: '0600'
            
            - name: Set cloud-init configurations
              ansible.builtin.shell: >
                qm set {{ GUEST.VM_VMID }}
                --ciuser {{ CLOUD_INIT_USER }}
                --cipassword {{ CLOUD_INIT_PASSWORD }}
                --sshkeys "/tmp/ssh_key_{{ GUEST.VM_VMID }}.pub"
                --ciupgrade 0
                --ipconfig0 'ip=dhcp'
                --ipconfig1 ''
                --searchdomain "local"

            - name: Remove temporary SSH key file
              ansible.builtin.file:
                path: "/tmp/ssh_key_{{ GUEST.VM_VMID }}.pub"
                state: absent

    - name: Finalize
      block:
        - name: Convert VM to template
          ansible.builtin.command:
            cmd: qm template {{ GUEST.VM_VMID }}

        - name: Verify template creation
          community.general.proxmox_vm_info:
            api_user: "{{ PROXMOX_USER }}@pam"
            api_password: "{{ PROXMOX_PASSWORD }}"
            api_host: "{{ PROXMOX_HOST }}"
            node: "{{ PROXMOX_NODE }}"
            vmid: "{{ GUEST.VM_VMID }}"
          register: FINAL_VM_INFO

        - name: Cleanup modified image file
          ansible.builtin.file:
            path: "{{ DESTINATION_PATH }}.modified"
            state: absent
          when: FINAL_VM_INFO is defined and FINAL_VM_INFO.proxmox_vms | length > 0

        - name: Display results
          ansible.builtin.debug:
            msg:
              - "Download Result = {{ DOWNLOAD_RESULT }}"
              - "Resize Result = {{ RESIZE_RESULT }}"
              - "VM Info = {{ FINAL_VM_INFO }}"