---
- name: Proxmox Cloud Image VM Template Provisioning (Environment)
  hosts: localhost
  gather_facts: false
  roles:
    - role: env_validation

- name: Proxmox Host Preparation and VM Provisioning
  hosts: all
  become: yes
  gather_facts: false
  vars:
    image_download_timeout: 600
    image_download_retries: 30
    image_download_delay: 10
  roles:
    - role: proxmox_validation
    - role: image_download
    - role: image_modify
    - role: cloudinit_config
    - role: vm_remove
    - role: vm_create