- name: Guest Master Configuring
  hosts: master
  become: yes
  gather_facts: no
  tasks:
    - name: Wait for SSH to be available on master nodes
      wait_for_connection:
        timeout: 300

    - name: Gather facts
      setup:

  roles:
    - role: master_config

- name: Guest Minion Configuring
  hosts: minion
  become: yes
  gather_facts: no
  tasks:
    - name: Wait for SSH to be available on minion nodes
      wait_for_connection:
        timeout: 300

    - name: Gather facts
      setup:

  roles:
    - role: minion_config
